version: '3'

services:
  local-spark:
    image: local-spark
    container_name: local-spark
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      METADATA_DRIVERNAME: postgresql
      METADATA_HOST: postgres
      METADATA_PORT: '5435'
      METADATA_USERNAME: spark
      METADATA_PASSWORD: spark
      METADATA_DATABASE: spark
    volumes:
      - ./godata2023:/opt/spark/work-dir/godata2023

  minio:
    image: 'minio/minio:RELEASE.2023-07-21T21-12-44Z'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: godata2023
      MINIO_SECRET_KEY: godata2023
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 godata2023 godata2023; /usr/bin/mc rm -r --force myminio/godata2023; /usr/bin/mc mb myminio/godata2023; /usr/bin/mc policy download myminio/godata2023; exit 0; "